### ISSUE TITLE
Enhancement Request: merge/overlay/background function

### ISSUE THREAD

**Issue by sdgathman** [hellerbarde/stapler#22]
This was the most used function of pdftk by me.  You have a preprinted form such as checks or Avery label sheets.  When developing the template or app to print on the form, you need to check alignment.  You could do this by actually printing on the forms.  In the case of labels, you could print outlines in a well tested app like glabels, and print those on paper, then print the label data on the same paper.  But those methods waste forms, paper, and ink.

With overlay, you have a PDF of the form, and your app prints the data to another PDF, then you overlay them to see that the data aligns with the form fields, or the addresses align with the label outlines.

An example pdftk command was:
$ pdftk file1.pdf background file2.pdf output combinedfile.pdf

The fill_form feature requested elsewhere sounds similar, but seems to be something about the PDF form fill feature, which is unrelated to simply overlaying pages.

**Comment by sdgathman** [comment]
I implemented this, it was pretty easy.  Might want multibackground as well (repeat background on all pages).

**Comment by sdgathman** [comment]
https://github.com/sdgathman/stapler/commit/d73d465c034a109d695f3a6f39920e6863937c4c

**Comment by hellerbarde** [comment]
I believe I just merged that ;)
