### ISSUE TITLE
enable 128 bit encryption

### ISSUE THREAD

**Issue by duffee** [hellerbarde/stapler#37]
When encrypting PDFs, the [PdfFileWriter](https://pythonhosted.org/PyPDF2/PdfFileWriter.html) class uses 40 bit encryption by default, but the `encrypt` function has a `use_128bit=True` option available.  It would be nice to add a command line option to use the 128 bit encryption, probably on [line 52 of iohelper.py](https://github.com/hellerbarde/stapler/blob/master/staplelib/iohelper.py#L52)

**Comment by queue-tip** [comment]
I don't think this is an issue. By default, PdfFileWriter uses 128-bit encryption not 40-bit.
