### ISSUE TITLE
need to deal with logical page numbers

### ISSUE THREAD

**Issue by jheidemann** [hellerbarde/stapler#44]
A feature request:

stapler needs to deal with logical page numbers in addition to physical page numbers.
That is, if my document starts with page i, ii, iii, iv before 1, I need to know that logical page iv is physical page 4, and logical page 1 is physical page 5.

It turns out logical page numbers are... fun .... in PDF.  In addition, logical page numbers are hard to integrate with stapler syntax, since it assumes page ranges are always in the form 1-2 or 1-end.

As a first step, I implemented a new command list-logical code that lists the logical page numbers and what the corresponding physical page is.  A skilled user can use shell programming this list to tell stapler what physical pages to change.

I will attach the patch shortly.

**Comment by jheidemann** [comment]
Patch is now in a pull request from jheidemann/stapler

**Comment by hellerbarde** [comment]
I believe this feature is merged. (btw, yes, logical page numbers are real ...fun... in PDFs ;)

**Comment by jheidemann** [comment]
Thanks!
