### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by sschwarzer** [hellerbarde/stapler#46]
I was looking for a PdfTk replacement and saw a recommendation of Stapler.

I am mostly interested in the `background` feature and saw that it was implemented in Stapler on Github. It took me a while to realize that while the feature was added in 2016, no release had been done since then to actually *deliver* the `background` feature.

It would be great if you could release a new version, so users (who are unlikely to look for and clone the repository) can actually use the new feature (and maybe others).

If there are things "half-done" that keep you from a release, this should be documented. (Or maybe it *is* documented, but I didn't find it.)

**Comment by hellerbarde** [comment]
Yeah, sorry. I have some time scheduled over the weekend. Hopefully we can have a release then. With Python 3 and everything.

**Comment by rapgro** [comment]
#54

**Comment by tjanez** [comment]
:+1:, now that Python 3 support is merged, a new release should be made.
(Perhaps #61 should be merged beforehand?).

The same request is in #51.

**Comment by corollari** [comment]
Also requested in #60.

**Comment by hellerbarde** [comment]
Done. Sorry for the delay :)
