### ISSUE TITLE
conflict with more-itertools

### ISSUE THREAD

**Issue by MaximLeyenson** [hellerbarde/stapler#53]
I have a conflict between Stapler and more-itertools on my Mint system which I decribed in details [here](https://github.com/erikrose/more-itertools/issues/295). 

The answer I received is that 

> `more-itertools` doesn't support Python 2 anymore. You can use version 5.0.0 (`pip install more-itertools==5.0.0`), which was the last version that worked on Python 2.7.
> 
> Stapler ought to change their [setup.py](https://github.com/hellerbarde/stapler/blob/master/setup.py#L16) to indicate < 6.0.0.

(I will try downgrading more-itertools manually, but I believe some better solution is needed)

Thank you for your great package,
 Maxim.

**Comment by bbayles** [comment]
See https://github.com/hellerbarde/stapler/pull/52 for a fix.

**Comment by MaximLeyenson** [comment]
> See #52 for a fix.

Thank you, bbayles!

**Comment by hellerbarde** [comment]
Thanks everyone for helping out :)

A new release is out on PyPI. version 1.0.0b1. Please test it and report bugs, if you find them.
