### ISSUE TITLE
Needs python3 support for Fedora 31

### ISSUE THREAD

**Issue by maitra** [hellerbarde/stapler#54]
Fedora 31 is dropping support for python2 so would be very helpful to move stapler to python3.

**Comment by maitra** [comment]
Actually python2 itself is achieving end-of-life in January 2020: see [https://pythonclock.org/](url) so this is important for more reasons that Fedora 31's dropping of support!

**Comment by vstoykov** [comment]
#20 is addressing this but is not merged yet but there is no response from the owner.

**Comment by maitra** [comment]
#20 replaces PyPDF2 with pypdf but that is not needed any more because PyPDF2 is supported on python3. So I am not sure how useful his changes are with regard to PyPDF2, however the other changes are likely adequate. Regardless, this project needs to be moved to python3 or will be obsoleted.

**Comment by maitra** [comment]
#20 replaces PyPDF2 with pypdf but that is not needed any more because PyPDF2 is supported on python3. So I am not sure how useful his changes are with regard to PyPDF2, however the other changes are likely adequate. Regardless, this project needs to be moved to python3 or will be obsoleted.

**Comment by frenzymadness** [comment]
It seems that the porting won't be hard so I'll prepare a new PR soon without new/changed dependencies.
