### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by htgoebel** [hellerbarde/stapler#60]
Python 2 is end-of-life 2019-12-31, Many Python libraries and projects, including Pillow, are [dropping Py2-support end of the year](https://python3statement.org/), Linux distributions are quickly dropping python2 libraries.

Looks like it's time to port to Python 3 :-)

**Comment by tjanez** [comment]
Python 3 support was added in #55.

**Comment by goodevilgenius** [comment]
The version installed through `pip` doesn't have those changes (https://pypi.org/project/stapler/#history). When will PyPi get updated with a more recent version?

**Comment by hellerbarde** [comment]
it has been done. version 1.0.0b1 is out. Please test it and let me know of any issues, so I can make a proper version 1.0.0 with the least amount of bugs ;)

**Comment by hellerbarde** [comment]
I will close this issue, please make a new issue if problems arise.
