### ISSUE TITLE
CI is not working

### ISSUE THREAD

**Issue by hellerbarde** [hellerbarde/stapler#70]
Even though we now have a nice shiny CI, it seems like I didn't set it up correctly on my (repo-owner) end. If someone can tell me which buttons to press in which order, I'd be delighted to do the tippy-tappy routine accordingly.

**Comment by Frenzie** [comment]
Under Settings → Actions you can set it to "Enable local and third party Actions for this repository." I think that should be all that's necessary.

**Comment by corollari** [comment]
I previously attached a screenshot of the process [in a comment](https://github.com/hellerbarde/stapler/pull/67#discussion_r382946426).
