### ISSUE TITLE
more-itertools<6.0.0

### ISSUE THREAD

**Issue by frenzymadness** [hellerbarde/stapler#71]
Hello.

As far as I can tell, there is no need to limit the latest version of more-itertools. All of the stapler's tests are passing with more-itertools 7.2.0 (the version we have in Fedora) and also with the latest version 8.2.0.

Could you please remove the upper limit and refresh poetry.lock?

**Comment by corollari** [comment]
#74 will remove the dependency on more_itertools once merged.

**Comment by corollari** [comment]
Fixed by #74
