### ISSUE TITLE
There is no .deb package

### ISSUE THREAD

**Issue by silash35** [hellerbarde/stapler#72]
Hi, I'm new around here so I'm sorry about anything.

Well, I'm learning Qt, so I decided to develop a graphical interface for Ghostscript and Stapler (Read about it at https://github.com/silash35/qpdftools). My goal is to gradually eliminate Ghostscript and use only the Stapler.

I am currently trying to make a debian package from "Qpdf Tools", but as it is just an interface for Ghostscript and Stapler these two programs need to be installed as a dependency. And that's where the problem is. The Stapler is not distributed as a .deb package so there is no way for me to place the stapler as an installation dependency.

What I would like to (Try) to do was a Stapler .deb package and leave it in this github for easy installation. And then, anyone who wanted to install Qpdf Tools would have to come here first to download the .deb from Stabler. I was wondering if I can do this and how to do it?

**Comment by silash35** [comment]
Wait, a find a solution!
I will put a "pip install stapler" on the postinst script on the .deb file.

**Comment by corollari** [comment]
Glad you found a solution, note that using `pip install stapler` assumes that both python and pip are installed, so you might want to declare these as package dependencies.
